version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      - POSTGRES_USER=luiz
      - POSTGRES_PASSWORD=stuff123
      - POSTGRES_DB=stuff
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
