import { z } from "zod";
import { commonSuccessResponses, commonErrorResponses } from "../../../../../types/http/responses";

export const aiFunctionalitiesRoutesDocs = {
    describeImage: {
        description: "Describe the objects in an image stored in Supabase S3 using a Bedrock agent. The agent receives a strict context and an optional user prompt, and returns a raw JSON with all detected objects and their attributes as per the Stuff system rules.",
        tags: ["ai-functionalities"],
        body: z.object({
            key: z.string().min(1).describe("S3 object key for the image (e.g. images/ai/1234.png)"),
            contextPrompt: z.string().optional().describe("Additional context for the agent (optional)")
        }),
        response: {
            200: z.unknown().describe("Raw JSON output from the agent, mapping object names to their attributes and descriptions."),
            400: commonErrorResponses[400],
            401: commonErrorResponses[401],
            500: commonErrorResponses[500]
        },
        security: [{ bearerAuth: [] }]
    },

    generatePresignedUrl: {
        tags: ["ai-functionalities"],
        summary: "Generate a presigned URL for uploading an image to Supabase S3 (images/ai)",
        description: "Returns a presigned URL and a generated S3 key for uploading an image. The filename is generated by the backend.",
        response: {
            200: z.object({
            url: z.string().url().describe("Presigned URL for image upload"),
            key: z.string().describe("S3 object key where the image should be uploaded")
            }),
            400: z.object({
            error: z.string().describe("Error message")
            })
        },
        security: [{ bearerAuth: [] }]
        }
};
